title: CarVerge
description: EV and modern automotive guides and reviews
theme: minima
baseurl: "/carverge"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
